### PR TITLE
fix: image loading when using markdown img and bigImageUrl

### LINKED ISSUE #333: Loads old, incorrect, picture from it's cache instead of new picture
I'm using Home Assistant to send a picture in a Gotify notification when a cctv camera is triggered. It's working and has been working since I started using last July. The pictures have a name and a number ie Drive1, Front3, Side1 etc. The number is incremented up to 100 then reset and starts from 1 again. ie Drive98 then Drive 99 then back to Drive1 then Drive2 etc.
The problem is that sometimes an old picture is served up from the app's cache instead of  the new picture. Clearing the cache stops it happening for a while, then it does it again.

This has been doing it since I started using it. It's annoying and I have put up with it until now but it's happening more often and has finally made me annoyed enough report it.

The way the pictures are handled in Home Assistant means that the numbers added to the picture name aren't always consecutive and can have quite a few left out, ie Drive 34 may be followed by Drive 45 then Drive46 then Drive50 etc. Which means that it can be a day, or a week or more, before a picture is sent with the same number as one already in the cache.
Is there anything that can be done to the app to correct this?

### PR DESCRIPTION
**Pull request by jmattheis**
Fixes #333

When receiving a message with the same image in the markdown body and in the extras client::notification.bigImageUrl, then there is a clash on the file system.

One request succeeds and the other fails with the following error. This commit ensures that there is only one coil image loader instance, so that there shouldn't be file system race conditions.

    WebSocket(1): received message {"id":845,"appid":21,...}
    Failed - http://192.168.178.2:8000/1.jpg?v=1718369188 - java.lang.IllegalStateException: closed
    java.lang.IllegalStateException: closed
        at okio.RealBufferedSource.rangeEquals(RealBufferedSource.kt:466)
        at okio.RealBufferedSource.rangeEquals(RealBufferedSource.kt:130)
        at coil.decode.SvgDecodeUtils.isSvg(DecodeUtils.kt:19)
        at coil.decode.SvgDecoder$Factory.isApplicable(SvgDecoder.kt:104)
        at coil.decode.SvgDecoder$Factory.create(SvgDecoder.kt:99)
        at coil.ComponentRegistry.newDecoder(ComponentRegistry.kt:100)
        at coil.intercept.EngineInterceptor.decode(EngineInterceptor.kt:197)
        at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:42)
        at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:131)
        at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(EngineInterceptor.kt)
        at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(EngineInterceptor.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:130)
        at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:42)
        at coil.intercept.EngineInterceptor$execute$1.invokeSuspend(EngineInterceptor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
    Successful (NETWORK) - http://192.168.178.2:8000/1.jpg?v=1718369188

---

The problem is reproducible: host a big image (20mb or more nearly trigger the bug 100%) on a server. When this message
```json
{
  "title": "Title",
  "message": "![](http://192.168.178.2:8000/1.jpg?v=VERSION)",
  "priority": 5,
  "extras": {
    "client::display": {
      "contentType": "text/markdown"
    },
    "client::notification": {
      "bigImageUrl": "http://192.168.178.2:8000/1.jpg?v=VERSION"
    }
  }
}
```
is viewed on android, then either the bigImageUrl or the markdown image doesn't load correctly. Caching suppresses the issue, so replace VERSION with something unique, so the bug is triggered on every POST.
```
cat msg.json| sed -E "s/VERSION/`date +%s%N`/g" |http POST ':8080/message?token=TOKEN'
```

---

After this commit, I couldn't reproduce the problem anymore.

### CODE REVIEW

File: app/src/main/kotlin/com/github/gotify/CoilInstance.kt [hunk 1]
```diff
@@ -16,56 +16,72 @@ import java.io.IOException
 import okhttp3.OkHttpClient
 import org.tinylog.kotlin.Logger
 
-internal class CoilHandler(private val context: Context, private val settings: Settings) {
```
Comment (jmattheis) [inline app/src/main/kotlin/com/github/gotify/CoilInstance.kt:19]: @cyb3rko Would you mind reviewing this PR, it's related to #337.

Comment (jmattheis) [reply app/src/main/kotlin/com/github/gotify/CoilInstance.kt:19]: @cyb3rko Thanks for the review, what smaller comment do you mean?
